- op: replace
  path: /spec/replicas
  value: 2
- op: replace
  path: /spec/strategy
  value:
    blueGreen:
      activeService: demo
      previewService: demo-preview
      autoPromotionEnabled: false
