apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollout.yaml
  - service.yaml
  - analysis.yaml

configurations:
  - rollout-transform.yaml

configMapGenerator:
  - name: demo-config
    literals:
      - APP_ENV=local
      - FAIL_EVERY=0
      - SLOW_MS=0
